//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Packages/com.yusam.yusam-package/Runtime/GameInput/Input/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""DefaultMap"",
            ""id"": ""a650b00e-4fb3-497a-aedf-475c265387b6"",
            ""actions"": [
                {
                    ""name"": ""LeftStickVector2"",
                    ""type"": ""Value"",
                    ""id"": ""eff81156-b7ee-49c6-bb18-a26161dbcda2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""f847e1ab-5d92-491c-bf41-9fb593163a2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPadUpPress"",
                    ""type"": ""Button"",
                    ""id"": ""9abb9ddd-920e-4d2e-a956-326a8d22cc26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPadDownPress"",
                    ""type"": ""Button"",
                    ""id"": ""e3c75b70-eb3e-4ce5-85c2-5352975fea45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPadLeftPress"",
                    ""type"": ""Button"",
                    ""id"": ""28ad5d24-2240-48e9-a403-bb8601a40a00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPadRightPress"",
                    ""type"": ""Button"",
                    ""id"": ""095dc216-f209-41e4-9988-1549bb06b977"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftTriggerPress"",
                    ""type"": ""Button"",
                    ""id"": ""0512a264-51ee-4423-b427-6f07d4e5675a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBumperPress"",
                    ""type"": ""Button"",
                    ""id"": ""14829c4d-aa05-461f-b5b8-8652b3842f6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectPress"",
                    ""type"": ""Button"",
                    ""id"": ""95e5a03a-dfd4-469a-9e26-becec0ee3195"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartPress"",
                    ""type"": ""Button"",
                    ""id"": ""7e709532-6677-4aa3-a157-2615cb1acf69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickVector2"",
                    ""type"": ""Value"",
                    ""id"": ""8415e3b5-0774-4e7e-82f4-569761b2b34f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""c1cc5cfd-c56a-46b7-bc96-a8e94126d843"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPadUpPress"",
                    ""type"": ""Button"",
                    ""id"": ""0c4abd0f-815e-4686-b707-3b2182aac2de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPadDownPress"",
                    ""type"": ""Button"",
                    ""id"": ""fa59ac34-9b87-402c-9594-2e0f878005d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPadLeftPress"",
                    ""type"": ""Button"",
                    ""id"": ""48f03f51-f243-4dba-b69f-9f50bc909d17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPadRightPress"",
                    ""type"": ""Button"",
                    ""id"": ""627cb516-f82a-402d-b4e3-8391907f6ee8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTriggerPress"",
                    ""type"": ""Button"",
                    ""id"": ""e01ea1a5-b76a-43a0-b199-c829f84d45a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBumperPress"",
                    ""type"": ""Button"",
                    ""id"": ""a926e437-cee8-41b8-bf3a-b0b9f4a7459b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseVector2"",
                    ""type"": ""Value"",
                    ""id"": ""df999d59-01d0-4a81-85dc-523efc191b64"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseLeftPress"",
                    ""type"": ""Button"",
                    ""id"": ""a4165dab-774a-4653-b603-d003b38cb2ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseRightPress"",
                    ""type"": ""Button"",
                    ""id"": ""8da71c35-56b5-41c2-9549-4eced46a6cdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMiddlePress"",
                    ""type"": ""Button"",
                    ""id"": ""95eb9dd2-1156-427c-87cd-c80a99a00234"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterPress"",
                    ""type"": ""Button"",
                    ""id"": ""5735af78-3bae-434d-9ba1-e2a422e7cf10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpacePress"",
                    ""type"": ""Button"",
                    ""id"": ""a0cae4c4-5fdf-42e3-9a42-19f9874a8912"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EscapePress"",
                    ""type"": ""Button"",
                    ""id"": ""64df29dd-3d07-4e87-acb4-ee71a1b5330c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""9d7d66d7-5254-4223-ad43-3586d2bb3b0c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d1b48c8-f2f2-4501-bfb7-09a86bb40c13"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f3daa7d8-f22d-435a-aa86-314f7a50f707"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0f2ff1f9-22f7-483b-adfa-0212b3a244e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f3f4cc29-f509-4011-b67b-379acf7ec5cf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad"",
                    ""id"": ""4f097865-5fd9-46d7-bc66-c4f26e783fa2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""aa820473-f6a1-49b7-a779-472925968c9a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8581189e-56af-4927-be5e-7baf96f1f355"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""60ea3148-3a54-4ac8-a994-e24fac0e9431"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5cb6e848-60bd-4083-8f83-0368afbf9b2e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""62114ec0-a47c-4c4e-9cb0-2e55fe132999"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56bccff3-efdb-4502-aa6c-482b76f3e11a"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ce30e48-6b0c-4209-a1e7-59cf4ebf2525"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPadDownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e3c1d13-033f-4850-832f-cbf43199fcb1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPadLeftPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""371d83e6-e0bb-4997-ae9a-0e3e1f1021cb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPadRightPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3899795-82f8-4aec-9997-ed5532b6763e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPadUpPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b3a5e8-8ccc-462d-837b-e7be9249e972"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74630da0-567a-4345-b3fe-2ef71e1fb9dd"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6a69186e-c89a-4b6c-8567-8593a62ac188"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e611b6af-4898-405a-aebf-64e15dfd1ffb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e1f179c6-780c-40f1-911a-84f641d6d140"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c97eee87-84f1-4771-a714-507cbb1c975e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c439adab-fd36-4050-83cb-2e11e0cd9ea7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad"",
                    ""id"": ""1d343b6f-5c21-4a31-ae03-d28449767fcb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2e3e5775-9789-4f13-93b6-51dffa0c665f"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69f97a7e-0e33-4eb1-b1c3-02187d102819"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""125857b4-0828-45d5-aad0-02ef960015f3"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a30dfc86-bdf3-405f-b329-904361c09391"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8d0dd167-6d0c-491b-b4a1-ea2254691aa9"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0bbb0b9-1e9d-43d8-a7d4-cbf0383e781c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad2109b6-9899-44e2-a357-4456a8f2dc67"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPadUpPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""848a9415-2db6-40a8-8d2d-915436220fbd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPadDownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee77f42e-d8d2-4750-90f0-dd0a870353c3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPadLeftPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27020889-e0b5-4840-a369-d97a28ac51c2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPadRightPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcec46f9-24c3-40e7-854d-b7249dd7a52c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f420dab4-30cf-488b-b660-394b6489c2f7"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4106844e-d5b6-499f-920c-53a771a2e1c6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBumperPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf425513-ead9-41c5-a3e0-9900a9e28203"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBumperPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""146a4e12-8ad7-43bf-ad8e-eed4132dd36b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""205f921b-b8e9-4d6f-a7dc-6c467b6af3ee"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c5871f6-b27c-4675-aad3-71736c920699"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBumperPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d945dd89-e394-481b-9565-d7543a9a54d5"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBumperPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""dd66a318-20cc-4336-80c0-8a40edd7460e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d47376ae-43c9-460d-a7c5-cb24ff1322f1"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""121960e0-f03d-4316-bfeb-3d0d92eb06b4"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dbd2a9df-af77-4733-908d-b765b77806a6"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""357c90b5-5875-4661-98b5-e6b146a48402"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ffbdd54e-c96d-469b-8e11-80045c9bae4c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLeftPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfa91314-3df6-4c1b-8d7d-a71a7c62c475"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseRightPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25de6010-b252-46a0-b376-fd93a92dad7d"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMiddlePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""5dea1fb6-232a-4d29-8cdc-8fcf79cd353a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""316cd20e-69ee-460b-a4df-4be9b1eab3f3"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""012813c4-89ed-4474-ae50-9a7eb5f9e320"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8c7696a2-4cb5-4452-8046-de859f41c69f"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c301959c-dae9-4f9c-88c7-19b767510c11"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d7e6e2c4-1ff2-4f5c-935c-cec16f56e4f9"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51bdd3a4-9e77-41cb-b292-55730ec90ce6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpacePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f501f6e-a723-4295-9369-b1c338a3754e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultMap
        m_DefaultMap = asset.FindActionMap("DefaultMap", throwIfNotFound: true);
        m_DefaultMap_LeftStickVector2 = m_DefaultMap.FindAction("LeftStickVector2", throwIfNotFound: true);
        m_DefaultMap_LeftStickPress = m_DefaultMap.FindAction("LeftStickPress", throwIfNotFound: true);
        m_DefaultMap_LeftPadUpPress = m_DefaultMap.FindAction("LeftPadUpPress", throwIfNotFound: true);
        m_DefaultMap_LeftPadDownPress = m_DefaultMap.FindAction("LeftPadDownPress", throwIfNotFound: true);
        m_DefaultMap_LeftPadLeftPress = m_DefaultMap.FindAction("LeftPadLeftPress", throwIfNotFound: true);
        m_DefaultMap_LeftPadRightPress = m_DefaultMap.FindAction("LeftPadRightPress", throwIfNotFound: true);
        m_DefaultMap_LeftTriggerPress = m_DefaultMap.FindAction("LeftTriggerPress", throwIfNotFound: true);
        m_DefaultMap_LeftBumperPress = m_DefaultMap.FindAction("LeftBumperPress", throwIfNotFound: true);
        m_DefaultMap_SelectPress = m_DefaultMap.FindAction("SelectPress", throwIfNotFound: true);
        m_DefaultMap_StartPress = m_DefaultMap.FindAction("StartPress", throwIfNotFound: true);
        m_DefaultMap_RightStickVector2 = m_DefaultMap.FindAction("RightStickVector2", throwIfNotFound: true);
        m_DefaultMap_RightStickPress = m_DefaultMap.FindAction("RightStickPress", throwIfNotFound: true);
        m_DefaultMap_RightPadUpPress = m_DefaultMap.FindAction("RightPadUpPress", throwIfNotFound: true);
        m_DefaultMap_RightPadDownPress = m_DefaultMap.FindAction("RightPadDownPress", throwIfNotFound: true);
        m_DefaultMap_RightPadLeftPress = m_DefaultMap.FindAction("RightPadLeftPress", throwIfNotFound: true);
        m_DefaultMap_RightPadRightPress = m_DefaultMap.FindAction("RightPadRightPress", throwIfNotFound: true);
        m_DefaultMap_RightTriggerPress = m_DefaultMap.FindAction("RightTriggerPress", throwIfNotFound: true);
        m_DefaultMap_RightBumperPress = m_DefaultMap.FindAction("RightBumperPress", throwIfNotFound: true);
        m_DefaultMap_MouseVector2 = m_DefaultMap.FindAction("MouseVector2", throwIfNotFound: true);
        m_DefaultMap_MouseLeftPress = m_DefaultMap.FindAction("MouseLeftPress", throwIfNotFound: true);
        m_DefaultMap_MouseRightPress = m_DefaultMap.FindAction("MouseRightPress", throwIfNotFound: true);
        m_DefaultMap_MouseMiddlePress = m_DefaultMap.FindAction("MouseMiddlePress", throwIfNotFound: true);
        m_DefaultMap_EnterPress = m_DefaultMap.FindAction("EnterPress", throwIfNotFound: true);
        m_DefaultMap_SpacePress = m_DefaultMap.FindAction("SpacePress", throwIfNotFound: true);
        m_DefaultMap_EscapePress = m_DefaultMap.FindAction("EscapePress", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultMap
    private readonly InputActionMap m_DefaultMap;
    private List<IDefaultMapActions> m_DefaultMapActionsCallbackInterfaces = new List<IDefaultMapActions>();
    private readonly InputAction m_DefaultMap_LeftStickVector2;
    private readonly InputAction m_DefaultMap_LeftStickPress;
    private readonly InputAction m_DefaultMap_LeftPadUpPress;
    private readonly InputAction m_DefaultMap_LeftPadDownPress;
    private readonly InputAction m_DefaultMap_LeftPadLeftPress;
    private readonly InputAction m_DefaultMap_LeftPadRightPress;
    private readonly InputAction m_DefaultMap_LeftTriggerPress;
    private readonly InputAction m_DefaultMap_LeftBumperPress;
    private readonly InputAction m_DefaultMap_SelectPress;
    private readonly InputAction m_DefaultMap_StartPress;
    private readonly InputAction m_DefaultMap_RightStickVector2;
    private readonly InputAction m_DefaultMap_RightStickPress;
    private readonly InputAction m_DefaultMap_RightPadUpPress;
    private readonly InputAction m_DefaultMap_RightPadDownPress;
    private readonly InputAction m_DefaultMap_RightPadLeftPress;
    private readonly InputAction m_DefaultMap_RightPadRightPress;
    private readonly InputAction m_DefaultMap_RightTriggerPress;
    private readonly InputAction m_DefaultMap_RightBumperPress;
    private readonly InputAction m_DefaultMap_MouseVector2;
    private readonly InputAction m_DefaultMap_MouseLeftPress;
    private readonly InputAction m_DefaultMap_MouseRightPress;
    private readonly InputAction m_DefaultMap_MouseMiddlePress;
    private readonly InputAction m_DefaultMap_EnterPress;
    private readonly InputAction m_DefaultMap_SpacePress;
    private readonly InputAction m_DefaultMap_EscapePress;
    public struct DefaultMapActions
    {
        private @GameInputActions m_Wrapper;
        public DefaultMapActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftStickVector2 => m_Wrapper.m_DefaultMap_LeftStickVector2;
        public InputAction @LeftStickPress => m_Wrapper.m_DefaultMap_LeftStickPress;
        public InputAction @LeftPadUpPress => m_Wrapper.m_DefaultMap_LeftPadUpPress;
        public InputAction @LeftPadDownPress => m_Wrapper.m_DefaultMap_LeftPadDownPress;
        public InputAction @LeftPadLeftPress => m_Wrapper.m_DefaultMap_LeftPadLeftPress;
        public InputAction @LeftPadRightPress => m_Wrapper.m_DefaultMap_LeftPadRightPress;
        public InputAction @LeftTriggerPress => m_Wrapper.m_DefaultMap_LeftTriggerPress;
        public InputAction @LeftBumperPress => m_Wrapper.m_DefaultMap_LeftBumperPress;
        public InputAction @SelectPress => m_Wrapper.m_DefaultMap_SelectPress;
        public InputAction @StartPress => m_Wrapper.m_DefaultMap_StartPress;
        public InputAction @RightStickVector2 => m_Wrapper.m_DefaultMap_RightStickVector2;
        public InputAction @RightStickPress => m_Wrapper.m_DefaultMap_RightStickPress;
        public InputAction @RightPadUpPress => m_Wrapper.m_DefaultMap_RightPadUpPress;
        public InputAction @RightPadDownPress => m_Wrapper.m_DefaultMap_RightPadDownPress;
        public InputAction @RightPadLeftPress => m_Wrapper.m_DefaultMap_RightPadLeftPress;
        public InputAction @RightPadRightPress => m_Wrapper.m_DefaultMap_RightPadRightPress;
        public InputAction @RightTriggerPress => m_Wrapper.m_DefaultMap_RightTriggerPress;
        public InputAction @RightBumperPress => m_Wrapper.m_DefaultMap_RightBumperPress;
        public InputAction @MouseVector2 => m_Wrapper.m_DefaultMap_MouseVector2;
        public InputAction @MouseLeftPress => m_Wrapper.m_DefaultMap_MouseLeftPress;
        public InputAction @MouseRightPress => m_Wrapper.m_DefaultMap_MouseRightPress;
        public InputAction @MouseMiddlePress => m_Wrapper.m_DefaultMap_MouseMiddlePress;
        public InputAction @EnterPress => m_Wrapper.m_DefaultMap_EnterPress;
        public InputAction @SpacePress => m_Wrapper.m_DefaultMap_SpacePress;
        public InputAction @EscapePress => m_Wrapper.m_DefaultMap_EscapePress;
        public InputActionMap Get() { return m_Wrapper.m_DefaultMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultMapActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultMapActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultMapActionsCallbackInterfaces.Add(instance);
            @LeftStickVector2.started += instance.OnLeftStickVector2;
            @LeftStickVector2.performed += instance.OnLeftStickVector2;
            @LeftStickVector2.canceled += instance.OnLeftStickVector2;
            @LeftStickPress.started += instance.OnLeftStickPress;
            @LeftStickPress.performed += instance.OnLeftStickPress;
            @LeftStickPress.canceled += instance.OnLeftStickPress;
            @LeftPadUpPress.started += instance.OnLeftPadUpPress;
            @LeftPadUpPress.performed += instance.OnLeftPadUpPress;
            @LeftPadUpPress.canceled += instance.OnLeftPadUpPress;
            @LeftPadDownPress.started += instance.OnLeftPadDownPress;
            @LeftPadDownPress.performed += instance.OnLeftPadDownPress;
            @LeftPadDownPress.canceled += instance.OnLeftPadDownPress;
            @LeftPadLeftPress.started += instance.OnLeftPadLeftPress;
            @LeftPadLeftPress.performed += instance.OnLeftPadLeftPress;
            @LeftPadLeftPress.canceled += instance.OnLeftPadLeftPress;
            @LeftPadRightPress.started += instance.OnLeftPadRightPress;
            @LeftPadRightPress.performed += instance.OnLeftPadRightPress;
            @LeftPadRightPress.canceled += instance.OnLeftPadRightPress;
            @LeftTriggerPress.started += instance.OnLeftTriggerPress;
            @LeftTriggerPress.performed += instance.OnLeftTriggerPress;
            @LeftTriggerPress.canceled += instance.OnLeftTriggerPress;
            @LeftBumperPress.started += instance.OnLeftBumperPress;
            @LeftBumperPress.performed += instance.OnLeftBumperPress;
            @LeftBumperPress.canceled += instance.OnLeftBumperPress;
            @SelectPress.started += instance.OnSelectPress;
            @SelectPress.performed += instance.OnSelectPress;
            @SelectPress.canceled += instance.OnSelectPress;
            @StartPress.started += instance.OnStartPress;
            @StartPress.performed += instance.OnStartPress;
            @StartPress.canceled += instance.OnStartPress;
            @RightStickVector2.started += instance.OnRightStickVector2;
            @RightStickVector2.performed += instance.OnRightStickVector2;
            @RightStickVector2.canceled += instance.OnRightStickVector2;
            @RightStickPress.started += instance.OnRightStickPress;
            @RightStickPress.performed += instance.OnRightStickPress;
            @RightStickPress.canceled += instance.OnRightStickPress;
            @RightPadUpPress.started += instance.OnRightPadUpPress;
            @RightPadUpPress.performed += instance.OnRightPadUpPress;
            @RightPadUpPress.canceled += instance.OnRightPadUpPress;
            @RightPadDownPress.started += instance.OnRightPadDownPress;
            @RightPadDownPress.performed += instance.OnRightPadDownPress;
            @RightPadDownPress.canceled += instance.OnRightPadDownPress;
            @RightPadLeftPress.started += instance.OnRightPadLeftPress;
            @RightPadLeftPress.performed += instance.OnRightPadLeftPress;
            @RightPadLeftPress.canceled += instance.OnRightPadLeftPress;
            @RightPadRightPress.started += instance.OnRightPadRightPress;
            @RightPadRightPress.performed += instance.OnRightPadRightPress;
            @RightPadRightPress.canceled += instance.OnRightPadRightPress;
            @RightTriggerPress.started += instance.OnRightTriggerPress;
            @RightTriggerPress.performed += instance.OnRightTriggerPress;
            @RightTriggerPress.canceled += instance.OnRightTriggerPress;
            @RightBumperPress.started += instance.OnRightBumperPress;
            @RightBumperPress.performed += instance.OnRightBumperPress;
            @RightBumperPress.canceled += instance.OnRightBumperPress;
            @MouseVector2.started += instance.OnMouseVector2;
            @MouseVector2.performed += instance.OnMouseVector2;
            @MouseVector2.canceled += instance.OnMouseVector2;
            @MouseLeftPress.started += instance.OnMouseLeftPress;
            @MouseLeftPress.performed += instance.OnMouseLeftPress;
            @MouseLeftPress.canceled += instance.OnMouseLeftPress;
            @MouseRightPress.started += instance.OnMouseRightPress;
            @MouseRightPress.performed += instance.OnMouseRightPress;
            @MouseRightPress.canceled += instance.OnMouseRightPress;
            @MouseMiddlePress.started += instance.OnMouseMiddlePress;
            @MouseMiddlePress.performed += instance.OnMouseMiddlePress;
            @MouseMiddlePress.canceled += instance.OnMouseMiddlePress;
            @EnterPress.started += instance.OnEnterPress;
            @EnterPress.performed += instance.OnEnterPress;
            @EnterPress.canceled += instance.OnEnterPress;
            @SpacePress.started += instance.OnSpacePress;
            @SpacePress.performed += instance.OnSpacePress;
            @SpacePress.canceled += instance.OnSpacePress;
            @EscapePress.started += instance.OnEscapePress;
            @EscapePress.performed += instance.OnEscapePress;
            @EscapePress.canceled += instance.OnEscapePress;
        }

        private void UnregisterCallbacks(IDefaultMapActions instance)
        {
            @LeftStickVector2.started -= instance.OnLeftStickVector2;
            @LeftStickVector2.performed -= instance.OnLeftStickVector2;
            @LeftStickVector2.canceled -= instance.OnLeftStickVector2;
            @LeftStickPress.started -= instance.OnLeftStickPress;
            @LeftStickPress.performed -= instance.OnLeftStickPress;
            @LeftStickPress.canceled -= instance.OnLeftStickPress;
            @LeftPadUpPress.started -= instance.OnLeftPadUpPress;
            @LeftPadUpPress.performed -= instance.OnLeftPadUpPress;
            @LeftPadUpPress.canceled -= instance.OnLeftPadUpPress;
            @LeftPadDownPress.started -= instance.OnLeftPadDownPress;
            @LeftPadDownPress.performed -= instance.OnLeftPadDownPress;
            @LeftPadDownPress.canceled -= instance.OnLeftPadDownPress;
            @LeftPadLeftPress.started -= instance.OnLeftPadLeftPress;
            @LeftPadLeftPress.performed -= instance.OnLeftPadLeftPress;
            @LeftPadLeftPress.canceled -= instance.OnLeftPadLeftPress;
            @LeftPadRightPress.started -= instance.OnLeftPadRightPress;
            @LeftPadRightPress.performed -= instance.OnLeftPadRightPress;
            @LeftPadRightPress.canceled -= instance.OnLeftPadRightPress;
            @LeftTriggerPress.started -= instance.OnLeftTriggerPress;
            @LeftTriggerPress.performed -= instance.OnLeftTriggerPress;
            @LeftTriggerPress.canceled -= instance.OnLeftTriggerPress;
            @LeftBumperPress.started -= instance.OnLeftBumperPress;
            @LeftBumperPress.performed -= instance.OnLeftBumperPress;
            @LeftBumperPress.canceled -= instance.OnLeftBumperPress;
            @SelectPress.started -= instance.OnSelectPress;
            @SelectPress.performed -= instance.OnSelectPress;
            @SelectPress.canceled -= instance.OnSelectPress;
            @StartPress.started -= instance.OnStartPress;
            @StartPress.performed -= instance.OnStartPress;
            @StartPress.canceled -= instance.OnStartPress;
            @RightStickVector2.started -= instance.OnRightStickVector2;
            @RightStickVector2.performed -= instance.OnRightStickVector2;
            @RightStickVector2.canceled -= instance.OnRightStickVector2;
            @RightStickPress.started -= instance.OnRightStickPress;
            @RightStickPress.performed -= instance.OnRightStickPress;
            @RightStickPress.canceled -= instance.OnRightStickPress;
            @RightPadUpPress.started -= instance.OnRightPadUpPress;
            @RightPadUpPress.performed -= instance.OnRightPadUpPress;
            @RightPadUpPress.canceled -= instance.OnRightPadUpPress;
            @RightPadDownPress.started -= instance.OnRightPadDownPress;
            @RightPadDownPress.performed -= instance.OnRightPadDownPress;
            @RightPadDownPress.canceled -= instance.OnRightPadDownPress;
            @RightPadLeftPress.started -= instance.OnRightPadLeftPress;
            @RightPadLeftPress.performed -= instance.OnRightPadLeftPress;
            @RightPadLeftPress.canceled -= instance.OnRightPadLeftPress;
            @RightPadRightPress.started -= instance.OnRightPadRightPress;
            @RightPadRightPress.performed -= instance.OnRightPadRightPress;
            @RightPadRightPress.canceled -= instance.OnRightPadRightPress;
            @RightTriggerPress.started -= instance.OnRightTriggerPress;
            @RightTriggerPress.performed -= instance.OnRightTriggerPress;
            @RightTriggerPress.canceled -= instance.OnRightTriggerPress;
            @RightBumperPress.started -= instance.OnRightBumperPress;
            @RightBumperPress.performed -= instance.OnRightBumperPress;
            @RightBumperPress.canceled -= instance.OnRightBumperPress;
            @MouseVector2.started -= instance.OnMouseVector2;
            @MouseVector2.performed -= instance.OnMouseVector2;
            @MouseVector2.canceled -= instance.OnMouseVector2;
            @MouseLeftPress.started -= instance.OnMouseLeftPress;
            @MouseLeftPress.performed -= instance.OnMouseLeftPress;
            @MouseLeftPress.canceled -= instance.OnMouseLeftPress;
            @MouseRightPress.started -= instance.OnMouseRightPress;
            @MouseRightPress.performed -= instance.OnMouseRightPress;
            @MouseRightPress.canceled -= instance.OnMouseRightPress;
            @MouseMiddlePress.started -= instance.OnMouseMiddlePress;
            @MouseMiddlePress.performed -= instance.OnMouseMiddlePress;
            @MouseMiddlePress.canceled -= instance.OnMouseMiddlePress;
            @EnterPress.started -= instance.OnEnterPress;
            @EnterPress.performed -= instance.OnEnterPress;
            @EnterPress.canceled -= instance.OnEnterPress;
            @SpacePress.started -= instance.OnSpacePress;
            @SpacePress.performed -= instance.OnSpacePress;
            @SpacePress.canceled -= instance.OnSpacePress;
            @EscapePress.started -= instance.OnEscapePress;
            @EscapePress.performed -= instance.OnEscapePress;
            @EscapePress.canceled -= instance.OnEscapePress;
        }

        public void RemoveCallbacks(IDefaultMapActions instance)
        {
            if (m_Wrapper.m_DefaultMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultMapActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultMapActions @DefaultMap => new DefaultMapActions(this);
    public interface IDefaultMapActions
    {
        void OnLeftStickVector2(InputAction.CallbackContext context);
        void OnLeftStickPress(InputAction.CallbackContext context);
        void OnLeftPadUpPress(InputAction.CallbackContext context);
        void OnLeftPadDownPress(InputAction.CallbackContext context);
        void OnLeftPadLeftPress(InputAction.CallbackContext context);
        void OnLeftPadRightPress(InputAction.CallbackContext context);
        void OnLeftTriggerPress(InputAction.CallbackContext context);
        void OnLeftBumperPress(InputAction.CallbackContext context);
        void OnSelectPress(InputAction.CallbackContext context);
        void OnStartPress(InputAction.CallbackContext context);
        void OnRightStickVector2(InputAction.CallbackContext context);
        void OnRightStickPress(InputAction.CallbackContext context);
        void OnRightPadUpPress(InputAction.CallbackContext context);
        void OnRightPadDownPress(InputAction.CallbackContext context);
        void OnRightPadLeftPress(InputAction.CallbackContext context);
        void OnRightPadRightPress(InputAction.CallbackContext context);
        void OnRightTriggerPress(InputAction.CallbackContext context);
        void OnRightBumperPress(InputAction.CallbackContext context);
        void OnMouseVector2(InputAction.CallbackContext context);
        void OnMouseLeftPress(InputAction.CallbackContext context);
        void OnMouseRightPress(InputAction.CallbackContext context);
        void OnMouseMiddlePress(InputAction.CallbackContext context);
        void OnEnterPress(InputAction.CallbackContext context);
        void OnSpacePress(InputAction.CallbackContext context);
        void OnEscapePress(InputAction.CallbackContext context);
    }
}
